---
- name: install Yubico tools
  pacman:
    name: "{{ item }}"
  with_items:
    - yubikey-personalization-gui
    - yubikey-personalization
    - libusb-compat

- name: download yubikey-full-disk-encryption
  unarchive:
    src: https://github.com/agherzan/yubikey-full-disk-encryption/archive/master.zip
    dest: /tmp
    remote_src: yes
    owner: aurman
    group: aurman

- name: build yubikey-full-disk-encryption aur package
  shell: makepkg -csrf --noconfirm --needed --noprogressbar
  args:
    chdir: /tmp/yubikey-full-disk-encryption-master
  become_user: aurman

- name: install yubikey-full-disk-encryption aur
  shell: pacman -U --noconfirm *.pkg.tar.xz
  args:
    chdir: /tmp/yubikey-full-disk-encryption-master

- name: install ykfde.conf
  template:
    src: ykfde.conf.j2
    dest: /etc/ykfde.conf
    mode: 0600
