---
- name: install xorg
  pacman:
    name: "{{ item }}"
  with_items:
    - xorg-server
    - xf86-video-intel
    - xorg-xinput
    - xorg-xbacklight
    - xorg-xinit
    - xorg-xprop
    - xorg-xdpyinfo

- name: install xorg config files
  copy:
    src: "{{ item }}"
    dest: "/etc/X11/xorg.conf.d/{{ item }}"
  with_items:
    - 10-monitor.conf
    - 20-trackpad.conf
    - 30-intel.conf

- name: blacklist nouveau kernel module
  copy:
    src: nouveau_blacklist.conf
    dest: /etc/modprobe.d/nouveau_blacklist.conf

- name: install display-setup script
  copy:
    src: display-setup
    dest: /usr/local/bin/display-setup
    mode: 0755
