---
- name: install libvirt and tools
  pacman:
    name: "{{ item }}"
  with_items:
    - qemu
    - libvirt
    - virt-manager

- name: add user to libvirt group
  user:
    name: "{{ user }}"
    groups: libvirt
    append: yes

- name: install virtualization AUR tools
  aur:
    name: cloud-utils
    user: aurman

- name: enable libvirt service
  service:
    name: libvirtd
    state: started
    enabled: yes
