---
- name: install Rofi
  pacman:
    name: rofi

- name: install NetworkManager Rofi script
  aur:
    name: networkmanager-dmenu-git
    user: aurman

- name: install udiskie Rofi script
  aur:
    name: udiskie-dmenu-git
    user: aurman
