---
- name: install mutt
  pacman:
    name: mutt

- name: install isync
  pacman:
    name: isync

- name: install w3m
  pacman:
    name: w3m

- name: install msmtp
  pacman:
    name: msmtp

- name: create mbsync systemd timer file
  copy:
    src: mbsync.timer
    dest: /usr/lib/systemd/user/mbsync.timer

- name: create mbsync systemd service file
  copy:
    src: files/mbsync.service
    dest: /usr/lib/systemd/user/mbsync.service

- name: enable mbsync systemd timer
  systemd:
    name: mbsync.timer
    state: started
    enabled: yes
    user: yes
  become_user: "{{ user }}"
