---
- name: enable multilib pacman repo
  replace:
    dest: /etc/pacman.conf
    regexp: '\#\[multilib\]\n\#Include = /etc/pacman\.d/mirrorlist'
    replace: '[multilib]\nInclude = /etc/pacman.d/mirrorlist'

- name: install wine
  pacman:
    name: wine-staging
    update_cache: yes

- name: install some lib32 deps
  pacman:
    name: "{{ item }}"
  with_items:
    - lib32-gnutls
    - lib32-libldap
    - lib32-libpulse
