---
- name: enable multilib pacman repo
  lineinfile:
    path: /etc/pacman.conf
    regexp: "^#[multilib]\n#Include = /etc/pacman.d/mirrorlist\n"
    line: "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n"

- name: install wine
  pacman:
    name: wine-staging
    update_cache: yes

- name: install some lib32 deps
  pacman:
    name: "{{ item }}"
  with_items:
    - lib32-gnutls
    - lib32-libldap
