---
- name: ensure vim is not installed
  pacman:
    name: vim
    state: absent

- name: install NeoVim deps
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - python-neovim
    - python2-neovim
    - xsel
    - aspell
    - aspell-es
    - aspell-en

- name: install NeoVim
  pacman:
    name: neovim

- name: create .vim directory
  file:
    path: "~/.local/share/nvim/site/autoload"
    state: directory
    recurse: yes
  become_user: "{{ user }}"

- name: install Plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.local/share/nvim/site/autoload/plug.vim"
  become_user: "{{ user }}"

- name: install vimdiff
  shell: echo -e '#!/bin/sh\nexec nvim -d "$@"'  > /usr/bin/vimdiff && chmod 755 /usr/bin/vimdiff

- name: set vim as NeoVim
  file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    state: link
