---
- name: install NeoVim deps
  pacman:
    name: "{{ item }}"
  become: yes
  with_items:
    - python-neovim
    - python2-neovim
    - xsel
    - aspell
    - aspell-es
    - aspell-en

- name: install NeoVim
  pacman:
    name: neovim

- name: create .vim directory
  file:
    path: "~/.local/share/nvim/site/autoload"
    state: directory
    recurse: yes
  become_user: "{{ user }}"

- name: install Plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.local/share/nvim/site/autoload/plug.vim"
  become_user: "{{ user }}"
