---
- name: install OpenVPN
  pacman:
    name: openvpn

- name: install OpenVPN systemd resolved script
  aur:
    name: openvpn-update-systemd-resolved
    user: aurman

- name: install NetworkManager OpenVPN support
  pacman:
    name: networkmanager-openvpn

- name: enable and start systemd-resolved
  service:
    name: systemd-resolved
    state: started
    enabled: yes
