---
- name: install video tools
  pacman:
    name: "{{ item }}"
  with_items:
    - mpv
    - mkvtoolnix-gui
    - handbrake
    - ffmpeg

- name: install makemkv
  aur:
    name: makemkv
    user: aurman
