---
- name: install font awesome
  aur:
    name: ttf-font-awesome-4
    user: aurman

- name: install system fonts
  pacman:
    name: "{{ item }}"
  with_items:
    - ttf-hack
    - ttf-liberation
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
