---
- name: install font awesome
  aur:
    name: ttf-font-awesome-4
    user: aurman

- name: install system fonts
  pacman:
    name: "{{ item }}"
  with_items:
    - terminus-font
    - ttf-hack
    - ttf-liberation
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
    - adobe-source-code-pro-fonts

- name: install ttf-ms-fonts
  aur:
    name: ttf-ms-fonts
    user: aurman

- name: install nerd fonts
  aur:
    name: nerd-fonts-complete
    user: aurman

- name: set console font
  copy:
    src: vconsole.conf
    dest: /etc/vconsole.conf
