---
- name: install font awesome
  aur:
    name: ttf-font-awesome-4
    user: aurman

- name: install system fonts
  pacman:
    name: "{{ item }}"
  with_items:
    - terminus-font
    - ttf-hack
    - ttf-liberation
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra

- name: set console font
  copy:
    src: vconsole.conf
    dest: /etc/vconsole.conf
